[[redirects]]
  from = "/legislatie"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/documente"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/materiale/*"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/noutati/*"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/articol/*"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/autentificare"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/api/*"
  to = "https://vast-jade-duckling-veil.cyclic.app/api/:splat"
  status = 200